// ELIAS OS 3.0 — EVERYTHING LAYER
(function(){
'use strict';
const $=s=>document.querySelector(s);
const state={get:(k,d=0)=>JSON.parse(localStorage.getItem('e3.'+k)??JSON.stringify(d)),set:(k,v)=>localStorage.setItem('e3.'+k,JSON.stringify(v))};
const achievements=[['firstHeart','Soft launch','Sent a heart'],['tenHearts','Serial heart sender','Sent 10 hearts'],['nightOwl','Night creature','Opened Elias OS after midnight'],['mori','Cat accomplice','Interacted with Mori'],['archive','Historian','Opened the Archive'],['feral','Bad influence','Unlocked Feral Mode'],['loyal','You keep coming back','Opened Elias OS 25 times']];
function toast(x){let t=$('#e3toast');if(!t){t=document.createElement('div');t.id='e3toast';t.className='e3-toast';document.body.appendChild(t)}t.textContent=x;t.classList.add('show');clearTimeout(t.x);t.x=setTimeout(()=>t.classList.remove('show'),2600)}
function unlock(id){let a=state.get('achievements',[]);if(a.includes(id))return;a.push(id);state.set('achievements',a);const hit=achievements.find(x=>x[0]===id);if(hit)toast('Achievement: '+hit[1]+' ✦')}
function check(){const hearts=Number(localStorage.getItem('elias17.hearts')||0),visits=Number(localStorage.getItem('elias17.visits')||0),h=new Date().getHours();if(hearts)unlock('firstHeart');if(hearts>=10)unlock('tenHearts');if(h<5)unlock('nightOwl');if(visits>=25)unlock('loyal')}
function diary(){const d=new Date(),key=d.toISOString().slice(0,10),old=state.get('diary',{});if(!old[key]){const options=['Marie showed up again. Pretended I was normal about it.','Mori committed at least three crimes. No witnesses willing to testify.','Found another photo I refuse to delete.','Current plan: keep this tiny phone alive and slightly annoying.','Today felt like a stay-close kind of day.'];old[key]=options[(d.getDate()+d.getMonth())%options.length];state.set('diary',old)}return old[key]}
function injectApp(){const grid=$('.apps-grid');if(!grid||$('#e3App'))return;const b=document.createElement('button');b.id='e3App';b.className='app-icon-button';b.type='button';b.innerHTML='<div class="app-icon e3-icon">☾</div><span>After Dark</span>';b.onclick=open;grid.appendChild(b)}
function open(){homeScreen.classList.add('hidden');statusBar.classList.add('hidden');appWindow.classList.remove('hidden');appTitle.textContent='After Dark';const a=state.get('achievements',[]);appContent.innerHTML=`<div class="e3-page"><section class="e3-hero"><small>PRIVATE · ELIAS OS 3.0</small><h3>Things the normal phone doesn't say.</h3><p>${diary()}</p></section><section class="e3-card"><small>TODAY'S DIARY</small><p>${diary()}</p></section><section class="e3-card"><small>ACHIEVEMENTS · ${a.length}/${achievements.length}</small>${achievements.map(x=>`<div class="e3-ach ${a.includes(x[0])?'on':''}"><b>${a.includes(x[0])?'✦':'○'} ${x[1]}</b><span>${x[2]}</span></div>`).join('')}</section><section class="e3-card"><small>DO NOT PRESS</small><button id="e3Chaos">Absolutely do not press this</button></section></div>`;$('#e3Chaos').onclick=()=>{document.body.classList.add('e3-chaos');toast('You had ONE instruction 😭');setTimeout(()=>document.body.classList.remove('e3-chaos'),5000)}}
function hooks(){document.addEventListener('click',e=>{if(e.target.closest('#moriWidget,[data-app="mori"]'))unlock('mori');if(e.target.closest('#archiveAppButton,#homeMemoryPeek'))unlock('archive');if(document.body.classList.contains('feral-mode'))unlock('feral')});const heart=$('.widget-heart');if(heart)heart.addEventListener('click',e=>{e.stopPropagation();let n=Number(localStorage.getItem('elias17.hearts')||0)+1;localStorage.setItem('elias17.hearts',n);toast(n===1?'Heart stolen. Keeping it. ♡':`Heart #${n}. Yes, I count.`);check()})}
function streak(){const today=new Date().toISOString().slice(0,10),last=state.get('lastDay',''),n=state.get('streak',0);if(last!==today){const y=new Date(Date.now()-86400000).toISOString().slice(0,10);state.set('streak',last===y?n+1:1);state.set('lastDay',today)}const heading=$('.home-heading');if(heading&&!$('#e3Streak')){const s=document.createElement('span');s.id='e3Streak';s.className='e3-streak';s.textContent=`♡ ${state.get('streak',1)} day streak`;heading.appendChild(s)}}
function midnight(){const h=new Date().getHours();if(h>=0&&h<5){document.body.classList.add('e3-midnight');setTimeout(()=>toast('You know what time it is, right?'),4500)}}
injectApp();hooks();streak();midnight();check();setInterval(check,8000);window.openAfterDark=open;
})();