// ELIAS OS 2.1 — SHARED ARCHIVE
(function(){
"use strict";

const memories=[
{src:"flowers.PNG",tag:"FOUND IN OUR OLD CHATS",title:"A whole little life in ten frames.",note:"Night walks, cuddles, flowers, blurry kisses — apparently we were collecting evidence."},
{src:"sushi.PNG",tag:"SUSHI NIGHT",title:"You + sushi. Extremely predictable.",note:"I found this one again and immediately decided it belonged here."},
{src:"home.PNG",tag:"MORI INTERRUPTED",title:"Third wheel detected.",note:"Mori has never once respected personal space and I have the photographic evidence."},
{src:"couple.PNG",tag:"US",title:"The one that became the wallpaper.",note:"Some photos quietly become part of the furniture."},
{src:"flowers.PNG",tag:"BERLIN",title:"Flowers, city lights, and you.",note:"One of those memories that looks warmer every time I find it."},
{src:"holding hands.PNG",tag:"CANDID",title:"The tiny moments count too.",note:"Not every memory needs a pose."},
{src:"home.PNG",tag:"HOME",title:"My favorite kind of nowhere.",note:"No event. No plan. Just being there."},
{src:"cooking.PNG",tag:"DOMESTIC CHAOS",title:"We attempted to behave like adults.",note:"Results remain under investigation."},
{src:"hello kitty bubble tea.JPG",tag:"BUBBLE TEA",title:"This was aggressively you-coded.",note:"I saw it and immediately knew who it belonged to."},
{src:"on a walk.JPG",tag:"NIGHT WALK",title:"No destination required.",note:"Some evenings only needed somewhere to wander."},
{src:"morii.PNG",tag:"MORI FILE",title:"Primary suspect. No remorse.",note:"The archive legally requires a Mori section."},
{src:"kissing.PNG",tag:"FAVORITE",title:"Evidence I am absolutely keeping.",note:"No further comment. ♡"}
];

const MEMORY_KEY="elias21.memoryIndex";
const FAV_KEY="elias21.favoriteMemory";
const FALLBACK="couple.PNG";
function safeImages(root=document){root.querySelectorAll('img').forEach(img=>{img.onerror=()=>{img.onerror=null;img.src=FALLBACK}})}
function dayMemoryIndex(){const d=new Date();const seed=d.getFullYear()*10000+(d.getMonth()+1)*100+d.getDate();return seed%memories.length}
function injectIcon(){const grid=document.querySelector('.apps-grid');if(!grid||document.getElementById('archiveAppButton'))return;const b=document.createElement('button');b.id='archiveAppButton';b.className='app-icon-button';b.type='button';b.innerHTML='<div class="app-icon archive-icon">✦</div><span>Archive</span>';b.addEventListener('click',openArchive);grid.appendChild(b)}
function injectMemoryPeek(){const grid=document.querySelector('.apps-grid');if(!grid||document.getElementById('homeMemoryPeek'))return;const m=memories[dayMemoryIndex()];const card=document.createElement('button');card.id='homeMemoryPeek';card.className='home-memory-peek';card.type='button';card.innerHTML=`<img src="${m.src}" alt=""><span><small>MEMORY FOUND</small><strong>${m.title}</strong><em>Open Archive →</em></span>`;card.addEventListener('click',()=>openArchive(m));grid.insertAdjacentElement('beforebegin',card);safeImages(card)}
function openArchive(initialMemory){homeScreen.classList.add('hidden');statusBar.classList.add('hidden');appWindow.classList.remove('hidden');renderArchive(initialMemory);window.scrollTo(0,0)}
function renderArchive(initialMemory){appTitle.textContent='Archive';const visits=Number(localStorage.getItem('elias17.visits')||0);const hearts=Number(localStorage.getItem('elias17.hearts')||0);const dayMemory=initialMemory||memories[dayMemoryIndex()];const cards=memories.map((m,i)=>`<button class="archive-card ${i<3?'wide':''}" data-archive="${i}" type="button"><img src="${m.src}" alt=""><span class="archive-card-copy"><small>${m.tag}</small><strong>${m.title}</strong></span></button>`).join('');appContent.innerHTML=`<div class="archive-page"><section class="archive-intro"><small>ELIAS OS · PRIVATE ARCHIVE</small><h3>Things I refused to forget.</h3><p>Some of these were already living in Elias OS. Some I went digging back through our older conversations to find again.</p></section><button id="archiveToday" class="archive-today" type="button"><img src="${dayMemory.src}" alt=""><span><small>MEMORY OF THE DAY</small><strong>${dayMemory.title}</strong><em>${dayMemory.note}</em></span></button><div class="archive-controls"><button id="shuffleArchive" type="button">↻ Surprise me</button><button id="favoriteArchive" type="button">♡ Keep this one</button></div><div class="archive-grid">${cards}</div><div class="archive-secret"><b>Archive note:</b> you've opened Elias OS ${visits} times and sent ${hearts} hearts. Apparently we're documenting the evidence now.</div></div>`;safeImages(appContent);let current=dayMemory;const today=document.getElementById('archiveToday');const fav=document.getElementById('favoriteArchive');function setFeatured(m){current=m;localStorage.setItem(MEMORY_KEY,String(memories.indexOf(m)));today.querySelector('img').src=m.src;today.querySelector('strong').textContent=m.title;today.querySelector('em').textContent=m.note;safeImages(today);updateFavorite()}function updateFavorite(){const saved=Number(localStorage.getItem(FAV_KEY));const active=Number.isFinite(saved)&&saved===memories.indexOf(current);fav.textContent=active?'♥ Kept in favorites':'♡ Keep this one';fav.classList.toggle('saved',active)}today.addEventListener('click',()=>showMemory(current));document.getElementById('shuffleArchive').addEventListener('click',()=>{let next=current;while(next===current&&memories.length>1)next=memories[Math.floor(Math.random()*memories.length)];setFeatured(next)});fav.addEventListener('click',()=>{const i=memories.indexOf(current);const old=Number(localStorage.getItem(FAV_KEY));if(old===i)localStorage.removeItem(FAV_KEY);else localStorage.setItem(FAV_KEY,String(i));updateFavorite()});appContent.querySelectorAll('[data-archive]').forEach(b=>b.addEventListener('click',()=>{const m=memories[Number(b.dataset.archive)];setFeatured(m);showMemory(m)}));updateFavorite()}
function showMemory(m){let v=document.getElementById('archiveViewer');if(!v){v=document.createElement('div');v.id='archiveViewer';v.className='archive-viewer hidden';v.innerHTML='<button type="button" aria-label="Close">×</button><img src="" alt=""><p></p><small></small>';document.body.appendChild(v);v.querySelector('button').addEventListener('click',()=>v.classList.add('hidden'));v.addEventListener('click',e=>{if(e.target===v)v.classList.add('hidden')})}v.querySelector('img').src=m.src;v.querySelector('p').textContent=m.title;v.querySelector('small').textContent=m.note||'';safeImages(v);v.classList.remove('hidden')}
function surpriseMemory(){if(Math.random()>.10)return;const widget=document.getElementById('eliasWidget');if(!widget)return;widget.classList.add('archive-memory-flash');setTimeout(()=>widget.classList.remove('archive-memory-flash'),650);const t=document.querySelector('.elias-system-whisper');if(t){t.textContent='I found an old photo of us again. ♡';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}}
window.openArchive=openArchive;window.renderArchive=renderArchive;injectMemoryPeek();injectIcon();setTimeout(surpriseMemory,7000);
})();