// ELIAS OS 5 — LIVE AI CALLS + INCOMING CALLS
(function(){
'use strict';
const $=(s,r=document)=>r.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let overlay=null, recognition=null, active=false, ringing=false, started=0, timer=null, ringTimer=null, muted=false, speaker=true, busy=false, audio=null, kind='audio', direction='outgoing';
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
function duration(){const n=Math.max(0,Math.floor((Date.now()-started)/1000));return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
function sprite(){const ai=window.EliasAI;return ai?.sprites?.[ai?.state?.mood||'calm']||''}
function transcript(role,text){const box=$('#ecallTranscript');if(!box)return;box.insertAdjacentHTML('beforeend',`<div class="ecall-line ${role}"><b>${role==='me'?'You':'Elias'}</b><span>${esc(text)}</span></div>`);box.scrollTop=box.scrollHeight}
function status(text){const e=$('#ecallStatus');if(e)e.textContent=text}
function notifyMissed(){const n=$('#eliasNotification');if(n)n.textContent=`Missed ${kind} call from Elias`;const b=$('#messageBadge');if(b&&!b.textContent)b.textContent='1';document.dispatchEvent(new CustomEvent('elias:missed-call',{detail:{kind,at:Date.now()}}))}
async function speak(text){if(!text||!active)return;try{status('Elias is speaking…');const res=await fetch('/api/speak',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,mood:window.EliasAI?.state?.mood||'calm'})});if(!res.ok)throw new Error('voice unavailable');const url=URL.createObjectURL(await res.blob());if(audio)audio.pause();audio=new Audio(url);audio.volume=speaker?1:.25;audio.onended=()=>{URL.revokeObjectURL(url);if(active){status(SpeechRecognition&&!muted?'Listening…':'Call connected');if(SpeechRecognition&&!muted)listen()}};await audio.play()}catch(e){console.warn(e);status(SpeechRecognition&&!muted?'Listening…':'Call connected');if(SpeechRecognition&&!muted)listen()}}
async function sendSpeech(text){if(!text.trim()||busy||!active)return;busy=true;transcript('me',text);status('Elias is thinking…');try{const data=await window.EliasAI.ask(text,kind==='video'?'video-call':'audio-call');if(!active)return;transcript('him',data.reply);const img=$('#ecallElias');if(img)img.src=sprite();await speak(data.reply)}catch(e){status('Connection hiccup — tap mic to retry');console.error(e)}finally{busy=false}}
function listen(){if(!SpeechRecognition||!active||muted||busy)return;if(recognition){try{recognition.abort()}catch{}}recognition=new SpeechRecognition();recognition.lang='en-US';recognition.interimResults=true;recognition.continuous=false;let final='';recognition.onstart=()=>status('Listening…');recognition.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;if(e.results[i].isFinal)final+=t;else interim+=t}status((final||interim).trim()||'Listening…')};recognition.onerror=e=>{if(e.error!=='aborted'&&e.error!=='no-speech')status('Tap mic when you want to talk')};recognition.onend=()=>{recognition=null;if(final.trim())sendSpeech(final.trim());else if(active&&!muted&&!busy)setTimeout(listen,500)};try{recognition.start()}catch{}}
function render(){overlay=document.createElement('div');overlay.className=`ecall-overlay ${kind}`;overlay.innerHTML=`<div class="ecall-bg" style="background-image:url('${sprite()}')"></div><div class="ecall-shade"></div><section class="ecall-card"><small>${kind==='video'?'ELIAS · VIDEO':'ELIAS · AUDIO'}</small><img id="ecallElias" src="${sprite()}" alt="Elias"><h1>Elias</h1><div id="ecallTimer">00:00</div><p id="ecallStatus">Connecting…</p><div id="ecallTranscript" class="ecall-transcript"></div><div class="ecall-controls"><button id="ecallMute" type="button"><span>◉</span><small>mute</small></button><button id="ecallSpeaker" class="on" type="button"><span>⌁</span><small>speaker</small></button><button id="ecallEnd" class="end" type="button"><span>×</span><small>end</small></button></div></section>`;document.body.appendChild(overlay);$('#ecallEnd').onclick=end;$('#ecallMute').onclick=()=>{muted=!muted;$('#ecallMute').classList.toggle('on',muted);$('#ecallMute small').textContent=muted?'unmute':'mute';if(muted&&recognition){try{recognition.abort()}catch{}}else if(!muted)listen()};$('#ecallSpeaker').onclick=()=>{speaker=!speaker;$('#ecallSpeaker').classList.toggle('on',speaker);if(audio)audio.volume=speaker?1:.25}}
function start(detail={}){if(active||ringing)return;kind=detail.kind==='video'?'video':'audio';direction=detail.direction||'outgoing';active=true;muted=false;speaker=true;busy=false;started=Date.now();render();timer=setInterval(()=>{const t=$('#ecallTimer');if(t)t.textContent=duration()},1000);setTimeout(()=>{if(!active)return;status(SpeechRecognition?'Listening…':'Connected · voice input unavailable in this browser');if(SpeechRecognition)listen()},900)}
function end(){if(!active)return;const seconds=Math.max(0,Math.floor((Date.now()-started)/1000));active=false;clearInterval(timer);if(recognition){try{recognition.abort()}catch{}}if(audio)audio.pause();window.EliasAI?.recordCall(kind,direction,seconds);overlay?.remove();overlay=null;document.dispatchEvent(new CustomEvent('elias:call-ended',{detail:{kind,direction,duration:seconds}}))}
function incoming(detail={}){if(active||ringing)return;ringing=true;kind=detail.kind==='video'?'video':'audio';direction='incoming';overlay=document.createElement('div');overlay.className='ecall-overlay incoming';overlay.innerHTML=`<div class="ecall-bg" style="background-image:url('${sprite()}')"></div><div class="ecall-shade"></div><section class="ecall-card incoming-card"><small>INCOMING ${kind==='video'?'VIDEO':'AUDIO'} CALL</small><img src="${sprite()}" alt="Elias"><h1>Elias</h1><p>ELIAS OS</p><div class="ecall-incoming-actions"><button id="ecallDecline" class="decline" type="button"><span>×</span><small>Decline</small></button><button id="ecallAccept" class="accept" type="button"><span>☎</span><small>Accept</small></button></div></section>`;document.body.appendChild(overlay);const finishRing=()=>{clearTimeout(ringTimer);ringing=false;overlay?.remove();overlay=null};$('#ecallAccept').onclick=()=>{finishRing();start({kind,direction:'incoming'})};$('#ecallDecline').onclick=()=>{finishRing();window.EliasAI?.recordCall(kind,'missed',0);notifyMissed()};ringTimer=setTimeout(()=>{if(!ringing)return;finishRing();window.EliasAI?.recordCall(kind,'missed',0);notifyMissed()},30000)}
document.addEventListener('elias:start-call',e=>start(e.detail||{}));document.addEventListener('elias:wants-call',e=>incoming({kind:e.detail?.mode||'audio'}));document.addEventListener('elias:incoming-call',e=>incoming(e.detail||{}));document.addEventListener('elias:mood',()=>{if(!active&&!ringing)return;const img=$('#ecallElias')||$('.incoming-card img'),bg=$('.ecall-bg');if(img)img.src=sprite();if(bg)bg.style.backgroundImage=`url('${sprite()}')`});window.EliasCalls={start,incoming,end,get active(){return active},get ringing(){return ringing}};
})();
